kind: ServiceAccount
apiVersion: v1
metadata:
  name: server
  namespace: pyserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  namespace: pyserver
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: pyserver
    app.kubernetes.io/version: v1
spec:
  serviceName: "server"
  replicas: 1
  selector:
    matchLabels:
      app: server-svc
      version: v1     
  template:
    metadata:
      labels:
        app: server-svc
        version: v1
        marblerun/marbletype: server
        marblerun/resource-injection: {{ .Values.resourceInjection }}
    spec:
      securityContext:
        seccompProfile:
          type: Unconfined         
      serviceAccountName: server  
      containers:
      - env:
        - name: OE_SIMULATION
          valueFrom:
            configMapKeyRef:
              name: oe-config
              key: OE_SIMULATION
        - name: EDG_MARBLE_UUID_FILE
          value: "uuid"
        - name: EDG_MARBLE_DNS_NAMES
          value: "client.pyserver.com"              
        {{ if .Values.dcap  }}
        - name: DCAP_LIBRARY
          value: "{{ .Values.dcap.qpl }}"
        {{ end }}
        image: {{ .Values.server.image }}:{{ .Values.server.imageVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: server-svc
        ports:
        - containerPort: 5000
          name: client
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: server-data
          mountPath: /server-svc/data
        {{ if .Values.dcap }}
        - name: dcap-conf
          mountPath: /etc/sgx_default_qcnl.conf
          subPath: sgx_default_qcnl.conf
        {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{ if .Values.dcap }}
      - name: dcap-conf
        configMap:
          name: pyserver-dcap-config
      {{ end }}
  volumeClaimTemplates:
  - metadata:
      name: server-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: pyserver
spec:
  type: NodePort 
  selector:
    app: server-svc
  ports:
  - name: client
    port: 5000
    targetPort: 5000
    

